#:kivy 1.11.1
#:import Window kivy.core.window.Window
#:import GameScreen shifttype.gamescreen.GameScreen


<Tile>:
    text: self.letter
    font_size: self.width / 2

<Reel>:
    orientation: 'vertical'

<ReelSlider>:
    size_hint: 1, None
    size:  self.width, self.width * len(self.children)
    orientation: 'vertical'

<GameArea>:
    orientation: 'horizontal'
    size_hint: self.num_letters/7.2, None

GameScreen:
    anchor_x: 'center'
    anchor_y: 'center'
